### ISSUE TITLE
Empty "/types/index.ts"

### ISSUE THREAD

**Issue by ronanyeah** [kklas/anchor-client-gen#2]
I noticed if I run this tool against an IDL with no "types" defined, the resultant `/types/index.ts` file will empty, which causes import errors in the other files.

I was able to fix the errors by putting `export default {};` in `/types/index.ts`.

**Comment by kklas** [comment]
Yea this is a bug. This is also related to the fact that in some cases unused imports get generated. Will fix this in the next patch.

**Comment by kklas** [comment]
should be fixed by b5c3009

**Comment by kklas** [comment]
I've published a beta release #10 which contains this fix. You can get it with `anchor-client-gen@beta`
